### ISSUE TITLE
Ошибка :

### ISSUE THREAD

**Issue by ZHNovell** [Evgen2/SmartTherm#1]
src/Web.cpp: In function 'void setup_web_common()':
src/Web.cpp:125:17: error: 'AUTOCONECT_FS_INITIALIZATION' was not declared in this scope
   FlashFS.begin(AUTOCONECT_FS_INITIALIZATION);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Web.cpp:125:17: note: suggested alternative: 'AUTOCONNECT_FS_INITIALIZATION'
   FlashFS.begin(AUTOCONECT_FS_INITIALIZATION);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 AUTOCONNECT_FS_INITIALIZATION
Compiling .pio\build\esp32dev\lib7fe\FS\FS.cpp.o
*** [.pio\build\esp32dev\src\Web.cpp.o] Error 1

**Comment by Evgen2** [comment]
macro AUTOCONNECT_FS_INITIALIZATION is defined in
.....pio\libdeps\esp32dev\AutoConnect\src\AutoConnectFS.h
24 #define AUTOCONNECT_FS_INITIALIZATION  true

As well you can find it  in example ..\.pio\libdeps\esp32dev\AutoConnect\examples\HelloWorld\HelloWorld.ino
